### PR TITLE
Update index.md - removeServerHeader

### PR DESCRIPTION
**Pull request by chyonek**
https://github.com/MicrosoftDocs/iis-docs/issues/186

### CODE REVIEW

**Comment by bariscaglar** [comment]
@shirhatti to make a small fix to the grammar and merge this.

**Comment by bariscaglar** [comment]
@shirhatti gentle ping.

**Comment by shirhatti** [comment]
Merged in 2f3954e2af7b1857bfe2ba2e9d3181c4e6192d31

Thanks for the PR!

**Comment by chyonek** [comment]
@shirhatti @bariscaglar bariscaglar Thank you for your check.  When will [docs page](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/) be updated?
By the way, can you fix it as follows? I noticed that "was" was duplicated.

**before**
Note: This attribute **was was** added in IIS 10.0 and does not work in versions of Windows prior to Windows Server, version 1709 or Windows 10, version 1709.

**after**
Note: This attribute **was** added in IIS 10.0 and does not work in versions of Windows prior to Windows Server, version 1709 or Windows 10, version 1709.

**Pull request closed without merging**
