### PR TITLE
Alt Text Inclusions

### PR DESCRIPTION
**Pull request by dereklh7**
Added missing alt text.

### CODE REVIEW

**Comment by dereklh7** [comment]
@Rick-Anderson @mcleblanc Final review - note that outstanding issues are being done in a separate pull request.

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
lots of alt text missing in one file, see the build report

**Comment by dereklh7** [comment]
@Rick-Anderson Instances of missing alt text has been added in another PR and is awaiting merge.

**Comment by dereklh7** [comment]
@Rick-Anderson All issues for this PR have been resolved. Awaiting final review.

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
<html>
<body>


iis/publish/using-the-ftp-service/using-fsrm-folder-quotas-with-ftp-in-iis-7.md | Suggestion | View | soshir | iis | iis-publish |   |   | Line 4: [Suggestion-PR only] Attribute 'description' with value 'Version Notes IIS 7.5 The FTP 7.5 service ships as a feature for IIS 7.5 in Windows 7 and Windows Server 2008 R2. IIS 7.0 The FTP 7.0 and FTP 7.5 services we...' is duplicated in 'get-started/whats-new-in-iis-7/what39s-new-for-microsoft-and-ftp-in-iis-7.md(4,14)', 'install/installing-publishing-technologies/installing-and-configuring-ftp-7-on-iis-7.md(4,14)', 'publish/using-the-ftp-service/adding-ftp-publishing-to-a-web-site-in-iis-7.md(4,14)', 'publish/using-the-ftp-service/configure-ftp-with-iis-manager-authentication-in-iis-7.md(4,14)', 'publish/using-the-ftp-service/configuring-ftp-firewall-settings-in-iis-7.md(4,14)'....
-- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>[iis/publish/using-the-ftp-service/using-fsrm-folder-quotas-with-ftp-in-iis-7.md](https://github.com/dereklh7/iis-docs/blob/AltText-3-23/iis/publish/using-the-ftp-service/using-fsrm-folder-quotas-with-ftp-in-iis-7.md)	Suggestion	[View](https://review.docs.microsoft.com/en-us/IIS/publish/using-the-ftp-service/using-fsrm-folder-quotas-with-ftp-in-iis-7?branch=pr-en-us-729)	soshir	iis	iis-publish			
Line 4: [Suggestion-[PR only](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/pr-only?branch=main)] Attribute 'description' with value 'Version Notes IIS 7.5 The FTP 7.5 service ships as a feature for IIS 7.5 in Windows 7 and Windows Server 2008 R2. IIS 7.0 The FTP 7.0 and FTP 7.5 services we...' is duplicated in 'get-started/whats-new-in-iis-7/what39s-new-for-microsoft-and-ftp-in-iis-7.md(4,14)', 'install/installing-publishing-technologies/installing-and-configuring-ftp-7-on-iis-7.md(4,14)', 'publish/using-the-ftp-service/adding-ftp-publishing-to-a-web-site-in-iis-7.md(4,14)', 'publish/using-the-ftp-service/configure-ftp-with-iis-manager-authentication-in-iis-7.md(4,14)', 'publish/using-the-ftp-service/configuring-ftp-firewall-settings-in-iis-7.md(4,14)'....

**Comment by Rick-Anderson** [comment]
Please fix last suggestion so we have a clean build.

**Comment by dereklh7** [comment]
@Rick-Anderson Fixed last suggestion per request.

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
