### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by tdykstra**
[Review URL](https://review.learn.microsoft.com/en-us/iis/?branch=pr-en-us-991)

### CODE REVIEW

**Review by wadepickett — APPROVED** [review]
Looks good!

I did find it to take a while to find where the install and get started topics were in the organization.  I would recommend adding a card for just that at the top left.

**Comment by wadepickett** [comment]
@tdykstra, just a heads up in case you forgot to merge this one.

**Comment by tdykstra** [comment]
I'm waiting for Paul to tell me how he wants to reorganize the links.

**Comment by paulcociuba** [comment]
From my side changes look great - I believe we can move this to the publish state.

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
