### PR TITLE
Migrate API ref

### PR DESCRIPTION
**Pull request by shirhatti**

### CODE REVIEW

**Comment by shirhatti** [comment]
@mairaw Can you review for metadata?

**Comment by shirhatti** [comment]
@bariscaglar FYI

**Comment by mairaw** [comment]
I'll create a PR with my changes so you can review them @shirhatti.

@ryanmajidi and @sudeepku I'd also propose that we add title suffixes to these new reference APIs so they don't clash and compete with existing .NET APIs. For example:
https://review.docs.microsoft.com/en-us/IIS/wmi-provider/xmlserializersection-class?branch=pr-en-us-303
vs.
https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.configuration.xmlserializersection?view=netframework-4.7.2

I also noticed there's a typo in one of the folder names:
ftp-extenisibility-reference should be ftp-extensibility-reference

**Comment by mairaw** [comment]
Also, I've noticed that the includes files are all scattered throughout the repo. Can't they be in a central location?

**Comment by shirhatti** [comment]
@ryanmajidi All these links are broken. Can you take a look?

https://github.com/MicrosoftDocs/iis-docs/blob/21149694874b47a4c2c8edfb17401d3f64a4432c/iis/TOC.yml#L957-L1008

**Comment by shirhatti** [comment]
I'm guessing we don't want links to MSDN. See https://github.com/MicrosoftDocs/iis-docs/blame/21149694874b47a4c2c8edfb17401d3f64a4432c/iis/ftp-extenisibility-reference/native-code-api-reference/ftp-native-code-extensibility-api-reference.md#L18

You should address this

**Comment by shirhatti** [comment]
Besides that, it's looking good to me.

@ryanmajidi What is our plan to have redirects?

**Comment by ryanmajidi** [comment]
I have a set of redirects that I have generated. Validation hasn't been done on them because it needs live pages but I can send them in email if you would like. Who do you want cc'ed? I will look into the links in the toc shortly but I suspect it is that leading whack that is giving us trouble. 

I suspect the msdn link is there because it was hardcoded in the original and thus wasn't converted when we extracted.

**Comment by shirhatti** [comment]
Can you do a scan for other hardcoded MSDN links?

**Comment by ryanmajidi** [comment]
vscode says 120 msdn links across 74 files. 75 of those (33 files) are to blogs.msdn.

**Comment by mairaw** [comment]
While I was doing my changes I also saw some reference content without the APIscan metadata. Does it mean that they didn't have that on MSDN as well? Also, there's a bunch of metadata fields that I don't recognize and don't think they're needed for docs. For example:

```
ms:assetid: Properties.T:Microsoft.Web.Media.SmoothStreaming.ClipContext
ms:mtpsurl: https://msdn.microsoft.com/en-us/library/microsoft.web.media.smoothstreaming.clipcontext_properties(v=VS.95)
ms:contentKeyID: 46307903
mtps_version: v=VS.95
--- 

It would also be good for me to understand which folders are being added here so I can validate the global settings I added to docfx.json.

**Comment by ryanmajidi** [comment]
the new folders are:
extensions/database-manager-reference
extensions/express-api-reference
extensions/search-engine-optimization-toolkit
extensions/smooth-streaming-client
extensions/smooth-streaming-management-rest-services
extensions/smooth-streaming-manifest-structure
extensions/url-rewrite
extensions/web-deployment--tool
extensions/web-platform-installer
extensions/web-playlist
ftp-extensibility-reference
web-development-reference
wmi-provider

**Comment by ryanmajidi** [comment]
For the apiscan issue, that was 99% exported straight out of caps so whatever the MD looked like is how it is in those folders. If there is a discrepancy my team has some tooling to patch the content. 

mtpsurl and mpts_versions are used to track when on msdn the content came from. And exists on all of the migrated content. I'm not familiar with the other two in the context of metadata but do know that they are used in the sre servers used for mtps.

**Comment by ryanmajidi** [comment]
I spoke with Sudeep about the metadata and his thought was that they are harmless to include and that if ever there is an issue and we need to dig up the original content that information will allow us to do so.

**Comment by shirhatti** [comment]
@mairaw This is the list of new directories

```
.
├── extensions
│   ├── express-api-reference
├── ftp-extenisibility-reference
│   └── native-code-api-reference
├── web-development-reference
│   ├── native-code-api-reference
│   └── native-code-development-overview
└── wmi-provider
```

**Comment by shirhatti** [comment]
> vscode says 120 msdn links across 74 files. 75 of those (33 files) are to blogs.msdn.

Ignoring the blogs.msdn links, can we get the rest of them addressed?

**Comment by shirhatti** [comment]
@ryanmajidi As an aside, do you have any tool to check if any of the outbound links point to non-existent resources?

**Comment by mairaw** [comment]
Yes @shirhatti. I was talking to Ke offline if we can run CATS scans in a branch and he said it's possible. I'll send you the info offline.

**Comment by mairaw** [comment]
Thanks for the list of folders. I'll double check what I did on docfx.json.

Also, what about the jscript examples? Should we remove those?

**Comment by shirhatti** [comment]
@mairaw I'm okay leaving the jscript examples in for this PR. We can remove them later, but let's not block on it

**Comment by ryanmajidi** [comment]
> > vscode says 120 msdn links across 74 files. 75 of those (33 files) are to blogs.msdn.
> 
> Ignoring the blogs.msdn links, can we get the rest of them addressed?

Typically editing content is outside of the scope of my teams work and our migration efforts. That said they will redirect when clicked anyways.

**Comment by ryanmajidi** [comment]
@shirhatti @mairaw Where are we at with being able to release this content? What needs fixed now vs what can wait for a post-release fix?

**Comment by shirhatti** [comment]
@mairaw Are there outages with OPS? I don't see the validation check on this PR?

**Comment by shirhatti** [comment]
> @mairaw Are there outages with OPS? I don't see the validation check on this PR?

Never mind. I spoke too soon

**Comment by mairaw** [comment]
Let's try one more time. If we get the same error, we should open a ticket for this.

**Comment by ryanmajidi** [comment]
@mairaw Looks like this passed with 0 warning and 0 failures.

**Pull request merged**
