### PR TITLE
 fix codesnippet reference

### PR DESCRIPTION
**Pull request by yishengjin1413**
Please check the codesnippet source files in this PR: https://github.com/dotnet/samples/pull/851

### CODE REVIEW

**Comment by mairaw** [comment]
Depends on https://github.com/MicrosoftDocs/iis-docs/pull/424

**Comment by bariscaglar** [comment]
@shirhatti This needs your review please.

**Comment by mairaw** [comment]
We first need to merge #424 and then close/reopen to see if it fixes the missing samples issue

**Comment by shirhatti** [comment]
@mairaw Looks like that didn't work 😕

**Comment by mairaw** [comment]
Actually, we'll need to merge the master branch here. Let me see if I can do this via GitHub UI.

**Comment by mairaw** [comment]
Ok, I think this is good to go now @shirhatti. The remaining warnings are unrelated.

**Comment by shirhatti** [comment]
I don't think this worked.  As an example, look at [this page](https://review.docs.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/cglobalmodule-class?branch=master)

The cpp snippet is just missing

https://github.com/MicrosoftDocs/iis-docs/pull/364/files#diff-a2ec07fb34bc5ada81e947c19f0d37bf

**Comment by mairaw** [comment]
Yes, it has.
https://review.docs.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/cglobalmodule-class?branch=pr-en-us-364

Once we merge to the working branch and then merge the working branch to master, you should be able to see the fix in the URL you have above.

**Comment by shirhatti** [comment]
> Yes, it has worked
 
I was looking at the wrong branch 🤦‍♂

**Pull request merged**
