### PR TITLE
Update warm-up-cache-nodes-on-application-request-routing.md

### PR DESCRIPTION
**Pull request by paulcociuba**
Removed the phrase about the procedure in step 1 being scriptable and being able to place it in a scheduled task since this feature does not exist.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@paulcociuba  looks good. Now I need to find the owner of this repo.

**Comment by Rick-Anderson** [comment]
@terrimorton who owns this repo. Looks like a lot of old PR's need to be reviewed.

**Comment by terrimorton** [comment]
Thanks, Rick. On it!

**Comment by shirhatti** [comment]
@pan-wang Can you confirm?

**Comment by bariscaglar** [comment]
It looks like the changes by Paul are already merged by other means. This pull request is out of date. Closing.

**Pull request closed without merging**
