### PR TITLE
Removed obsolete contents related to URLScan

### PR DESCRIPTION
**Pull request by lextm**
#403 and #418 showed that users might still be confused about URLScan.

This pull requests remove all related articles and unnecessary references.

### CODE REVIEW

**Comment by lextm** [comment]
@Rick-Anderson you might review and approve this.

I tried to remove the articles and references instead of adding notes to them saying they are obsolete, because the installers of URLScan were removed from Microsoft sites and new users on IIS 10 should not be able to install them any more.

Not sure if this is the right approach for obsolete contents.

**Review by tdykstra — APPROVED** [review]

**Comment by tdykstra** [comment]
@lextm can you please resolve the merge conflicts that resulted from merging PR #1015?

**Comment by lextm** [comment]
Sure. I will work on it soon.

**Comment by lextm** [comment]
@tdykstra Done. You can start review now.

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
