### PR TITLE
Merge to live

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@bariscaglar @shirhatti  30 second review please

**Comment by Rick-Anderson** [comment]
@ChrisSfanos if you can approve this, I'll merge to live. I don't know why we're running the build warning tool, we should probably remove that @shirhatti . We've got thousands of validation warnings we're probably never going to fix.

**Review by ChrisSfanos — APPROVED** [review]

**Comment by ChrisSfanos** [comment]
I approved it

**Comment by shirhatti** [comment]
I think it was this PR in which you made status checks mandatory- https://github.com/MicrosoftDocs/iis-docs/pull/558/files

**Pull request merged**
