### PR TITLE
added alt text

### PR DESCRIPTION
**Pull request by v-emilypr**

### CODE REVIEW

**Comment by v-emilypr** [comment]
**Global effort to fix build validation errors**

@Rick-Anderson, @mcleblanc

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
Can you  fix all `Line 4: [Suggestion-[PR only](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/pr-only?branch=main)] Attribute 'description'` warnings in the build report?

**Comment by v-emilypr** [comment]
@Rick Anderson requested change made.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by rick** [comment]
change is possible

**Pull request merged**
