### PR TITLE
requestFiltering denyStrings is regex

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
Clarified that the strings are evaluated as regex. Just tested this myself to be sure.

### CODE REVIEW

**Comment by bariscaglar** [comment]
@bangbingsyb can you confirm this change is correct? So we always do the request filtering with regex?

**Comment by bangbingsyb** [comment]
I looked at our implementation on how the Request Filtering Module scans URL/query string/headers based on denyStrings collection and saw we just performed simple string search - no regular expression matching logic. So I don't think the change in the PR is correct.

@DavidDeSloovere : Could you provide details of your test? What makes you believe denyStrings support regular expression?

I saw your serverfault answer: https://serverfault.com/questions/848515/does-iis-request-filtering-rules-use-regex-for-the-deny-strings

**Comment by DavidDeSloovere** [comment]
I don't know what happened here. Retesting this and it's not parsed as a regex but more like 'contains'. Sorry for your time.

**Comment by bangbingsyb** [comment]
@DavidDeSloovere Not a problem. The best way to confirm the detailed request processing logic is through capturing a failed request tracing (FREB) log and looking at the events from each module. If request filtering module is involved, the FREB log will tell whether it rejects the request or not, and maybe a reason is included as well.

**Comment by DavidDeSloovere** [comment]
@bangbingsyb Thanks. Never really used that feature before.

**Pull request closed without merging**
