### PR TITLE
Validation: Fix multiple issues 

### PR DESCRIPTION
**Pull request by annmariehitchcock**
This PR addresses the following issues:
docs-link-absolute
image-alt-text-duplicated
ms-author-invalid
description-missing
duplicate-descriptions

There are build warnings, but we were instructed not to fix duplicate title or H1 issues.

### CODE REVIEW

**Comment by annmariehitchcock** [comment]
Global effort to fix validation errors

@Rick-Anderson @mcleblanc

The Content & Learning team is fixing build validation errors on docs.microsoft.com. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. I’d very much appreciate your timely review and feedback on these changes I’ve suggested. Thanks!

**Comment by tfosmark** [comment]
@annmariehitchcock Please address the merge conflicts. Thanks!

**Comment by annmariehitchcock** [comment]
Merge conflict was addressed. Thank you!

**Review by tfosmark — APPROVED** [review]

**Comment by v-emilypr** [comment]
#please-close

**Pull request closed without merging**
