### PR TITLE
metadata clean-up

### PR DESCRIPTION
**Pull request by mairaw**
What I've done:
- Moved the most common settings to the docfx.json files
- Removed the manager metadata
- Changed ms.topic from article to conceptual ( or reference in the case of the configuration folder)
- Removed | Microsoft Docs from the titles. It's automatically added by the build
- Added an IIS search scope

I'm keeping the ms.technology values you had except for iss. So I'll request our team white list them.

### CODE REVIEW

**Comment by mairaw** [comment]
@Rick-Anderson can you review this PR?

**Comment by shirhatti** [comment]
@Rick-Anderson 	/ @mairaw I'm assuming you folks will handle merging this PR?

**Comment by mairaw** [comment]
I don't have permissions to do that. I'll ping @Rick-Anderson to see if he can do that.

**Comment by Rick-Anderson** [comment]
@mairaw 	thanks for doing this. You could have assigned the work to me. I owe you.

This *docfx.json* changes look good. @shirhatti 	are you happy with the following:

image

**Comment by Rick-Anderson** [comment]
@shirhatti do you want me to merge with live or do you normally take care of that?

**Comment by mairaw** [comment]
Thanks @Rick-Anderson. Wade had asked me to take care of this.

Yeah, this PR touched many files but it's following the same pattern as we did in our repos, so it should be ok. I also removed another docfx.json file from this repo because when I updated it, it didn't have any effect, so I think there's only one docset configured here.

I also requested the new ms.technology values today to our BI team, so all the IIS content should be in good shape next week.

**Pull request merged**
