### PR TITLE
[Bulk] Validation: Fix Missing Altext4

### PR DESCRIPTION
**Pull request by Roudabeh1348**
This PR fixes 62 missing alt text issues from 10 articles.

### CODE REVIEW

**Comment by Roudabeh1348** [comment]
@Rick-Anderson @mcleblanc This PR fixes validation warnings/suggestions per a platform-wide push to increase content health scores. Please review at your convenience and sign off or merge if you approve or let me know if I need to make any other changes. CC: @MonicaRush @snoviking

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@Roudabeh1348  please review the build report, lots of duplicate alt text 

image

**Comment by Roudabeh1348** [comment]
@Rick-Anderson I fixed the duplicate alt text issues with the PR which are in line 91 and 135 in the article  iis/publish/using-the-ftp-service/using-ftp-virtual-host-names-in-iis-7.md. The rest of the issues in the build report were out of scope but I can certainly take care of them if you wish me to do so.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
> The rest of the issues in the build report were out of scope but I can certainly take care of them if you wish me to do so.

They can be done in another PR. Probably best to fix all the alt text issues first. Thanks for asking.

**Pull request merged**
