### PR TITLE
fix: MD009

### PR DESCRIPTION
**Pull request by nschonni**
Trim trailing spaces

### CODE REVIEW

**Comment by mairaw** [comment]
I think this particular rule is tricky to do in a global way. Given that trailing two spaces creates a new line, in some cases, it creates some issues if you remove that.

For example:
https://docs.microsoft.com/en-us/IIS/application-frameworks/running-php-applications-on-iis/build-a-high-performance-php-stack-with-windows-iis-and-zend-server

Before
image

After
image

**Comment by nschonni** [comment]
It shouldn't touch any double trailing spaces, because it knows about that rule, but will trim any 2+ ones

**Comment by Rick-Anderson** [comment]
There's very little benefit to this change and some risk.

**Comment by mairaw** [comment]
But somehow it is trimming those given the example I just posted @nschonni. I'd close this PR.

**Comment by wadepickett** [comment]
@mairaw, yep, we are on the same page.

**Pull request closed without merging**
