### PR TITLE
Added PowerShell Examples w/IISAdministration

### PR DESCRIPTION
**Pull request by phbits**
Updated examples using IISAdministration module. It's unfortunately verbose since each write operation requires the configuration to be reloaded. Otherwise the following error is returned:

> The configuration object is read only, because it has been committed by a call to ServerManager.CommitChanges(). If write access is required, use ServerManager to get a new reference.

Tested on IIS10.

### CODE REVIEW

**Comment by jhkimnew** [comment]
@phbits, in order to avoid the error, you can also use [Start/Stop]-IISCommitDelay as the following example and you don't need to repeat to get a new section after each update command.
In the below example, $filteringRules was re-used. Do you want to update the examples?

```
Start-IISCommitDelay

$filteringRules = Get-IISConfigSection -CommitPath 'Default Web Site' -SectionPath 'system.webServer/security/requestFiltering' | Get-IISConfigCollection -CollectionName 'filteringRules' 
New-IISConfigCollectionElement -ConfigCollection $filteringRules -ConfigAttribute @{ 'name' = 'Block Image Leeching'; 'scanUrl' = $false; 'scanQueryString' = $false; 'scanAllRaw' = $false; } 

$Rule = Get-IISConfigCollectionElement -ConfigCollection $filteringRules -ConfigAttribute @{ 'name' = 'Block Image Leeching' } 
$ruleScanHeaders = Get-IISConfigCollection -ConfigElement $Rule -CollectionName 'scanHeaders' 
New-IISConfigCollectionElement -ConfigCollection $ruleScanHeaders -ConfigAttribute @{ 'requestHeader' = 'User-Agent' }

Stop-IISCommitDelay
```

**Comment by phbits** [comment]
Thanks for pointing out IISCommitDelay! Updated samples for: denyUrlSequences, fileExtensions, filteringRules, verbs

**Comment by phbits** [comment]
Two commits (5d31d12 & 8b493ec) are failing with what appears to be an internal error:

> ...failed, possibly due to transient errors from nuget servers. Please try to close and reopen the PR to see if the issue can be resolved. Otherwise, refer to the instructions here to resolve the build issue: https://opsdocs.azurewebsites.net/<snip>. If the issue still happens, open a ticket in http://SiteHelp.

Accessing opsdocs returned an HTTP 403 Forbidden.

Deleted/Created the two files and they both check out ok.
- iis-docs/iis/configuration/system.webServer/security/requestFiltering/filteringRules/filteringRule/index/samples/sample8.ps1
- iis-docs/iis/configuration/system.webServer/security/requestFiltering/filteringRules/filteringRule/appliesTo/index/samples/sample8.ps1

Shouldn't the Build Raw Log be internal only and not customer facing? The Open Publishing Online Build Report is sufficient for customers.

**Comment by jhkimnew** [comment]
@phbits: I am sorry but I don't know what's going on. Do you need any help from me for completing this PR? If so, please explain with more detail because I don't have much context about what you are trying to do with this.

**Comment by phbits** [comment]
@jhkimnew Thank you. PR=Pull Request. Thought that had something to do with the backend infrastructure. Open Publishing Online Build Report error message states the following. Closing this PR and will try to reopen.
> Please try to close and reopen the PR to see if the issue can be resolved.

**Comment by phbits** [comment]
reopening

**Comment by jhkimnew** [comment]
I see. Feel free assign the new PR to me (jhkimnew) and I will review it.

**Comment by phbits** [comment]
@jhkimnew The `close and reopen the PR` technique didn't work. The Open Publishing Online Build Report references the following link as a possible solution however I don't have access to it. Do you have access? If so, does it provide guidance to resolve the PR validation errors for commits: 5d31d12 & 8b493ec ?

> https://opsdocs.azurewebsites.net/en-us/opsdocs/partnerdocs/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch

If the above doesn't work, the last suggestion is as follows which is another website I don't have access to. So you or someone on your team would have to take ownership of the ticket and it's process.
> If the issue still happens, open a ticket in http://SiteHelp.

**Comment by jhkimnew** [comment]
@phbits:  Instead of reopening the same PR, I'd like to ask you to create a new PR with a single commit which combines all the updates you did here. Can you try that? If that still does not work, please let me know and I will investigate what is the root cause.

**Comment by shirhatti** [comment]
@phbits Ignore the intermediate failures. It was because of a temporal issue on docs.microsoft.com. The final PR including all the commits is building fine.

**Comment by shirhatti** [comment]
@jhkimnew You can squash and merge the PR if you're done signing off on it. [It's building fine](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C29%5C90f071cf-c002-b629-5e11-5bc968bb67ca%5CPullRequest%5C201811290051289809-276%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XVdtnTrhtqSIP5Ml%2F3p7nWIg13AeKKAReLzI3oJbVsY%3D&st=2018-11-29T19%3A33%3A43Z&se=2018-12-30T19%3A38%3A43Z&sp=r)

**Comment by jhkimnew** [comment]
@shirhatti Thanks for the information. I was not assigned to complete the PR. I was just reviewing the change is okay or not. So, I guess that @phbits can complete this PR. 

@phbits: Please correct me if I am wrong about that you can complete this PR.

**Comment by phbits** [comment]
@shirhatti Thanks for clearing up the PR commit errors.

@jhkimnew I don't have permission to merge this PR.

**Comment by phbits** [comment]
@shirhatti Thanks for merging this request! How long until docs.microsoft.com is updated? I thought it would be almost instant however after looking at the source they aren't picking up the new content. Guessing there's a backend sync or review process?

On a related note, shouldn't the [Build Raw Logs](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C29%5C90f071cf-c002-b629-5e11-5bc968bb67ca%5CPullRequest%5C201811290051289809-276%5Crawlog.txt?sv=2015-02-21&sr=b&sig=vkUDT6L2Tw4ACG8za%2BTYHwMebHyaQdttdmA1XEocmAo%3D&st=2018-11-29T00%3A48%3A48Z&se=2018-12-30T00%3A53%3A48Z&sp=r) be restricted to MS only? They seem unnecessarily verbose for external customers. The [report you referenced earlier](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C29%5C90f071cf-c002-b629-5e11-5bc968bb67ca%5CPullRequest%5C201811290051289809-276%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XVdtnTrhtqSIP5Ml%2F3p7nWIg13AeKKAReLzI3oJbVsY%3D&st=2018-11-29T19%3A33%3A43Z&se=2018-12-30T19%3A38%3A43Z&sp=r) is more than sufficient.

**Pull request merged**
