### PR TITLE
IdleTimeout - setting 00:00:00 disables idle timeout

### PR DESCRIPTION
**Pull request by TristankMS**
Has been a widely-understood but undocumented effect of setting idleTimeout to 0; should be documented and supported. See also https://stackoverflow.com/questions/1596267/how-to-disable-the-application-pool-idle-time-out-in-iis7

(incidentally, I didn't make the VB change at the bottom? Not visibly anyway...)

### CODE REVIEW

**Comment by bariscaglar** [comment]
Tristan, what do you mean by "I didn't make the VB change at the bottom? Not visibly anyway."?

**Comment by TristankMS** [comment]
When reviewing my change, there was a small change to the sample VB thing at the bottom, which wasn't part of the edit (below). The committed PR doesn't mention it, so I think we're good.

!code-vb[Main](processModel/samples/sample7.vb)] 
+[!code-vb[Main](processModel/samples/sample7.vb)]

**Comment by shirhatti** [comment]
There was no newline at the end of the file. It got added since I'm guessing the change was made via the in-browser editor.

We see that happen all the time 😄

**Comment by TristankMS** [comment]
Awesome! Thanks!

**Pull request merged**
