### PR TITLE
[BULK] validation: various

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
Changes to 27 topics: 

- preserve-view-not-set
- docs-link-absolute
- image-alt-text-duplicated
- yaml-duplicate-key
- description-missing
- duplicate-descriptions

There are build warnings, but we were told not to fix duplicate title or H1 issues.

Some of the new descriptions were shorter than our 100 char suggested length, but I left them unpadded because this is syntax reference. Let me know if you want us to add "Learn about . . ." or similar to bring the description length up.

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
Hi @Rick-Anderson @mcleblanc - I wanted to follow up with you about these validation fixes. Please let me know if you have any questions.

**Comment by tfosmark** [comment]
@TimShererWithAquent Please address the merge conflicts. Thanks!

**Comment by TimShererWithAquent** [comment]
@tfosmark Conflicts resolved -

**Review by tfosmark — APPROVED** [review]

**Comment by tfosmark** [comment]
@Rick-Anderson Please merge, or let us know if you have any concerns with these changes. Thank you!!

**Comment by tfosmark** [comment]
@TimShererWithAquent Please resolve the merge conflicts & we'll try again. Thanks!

**Comment by tfosmark** [comment]
@Rick-Anderson Ready for merge!

**Review by v-emilypr — APPROVED** [review]

**Review by Rick-Anderson — APPROVED** [review]

**Pull request merged**
