### PR TITLE
Validation: Fix descriptions 

### PR DESCRIPTION
**Pull request by annmariehitchcock**
This PR addresses the following issues:
duplicate-descriptions
description-missing

There are build warnings, but we were instructed not to fix duplicate title or H1 issues.

### CODE REVIEW

**Comment by annmariehitchcock** [comment]
Global effort to fix validation errors

@Rick-Anderson @mcleblanc

The Content & Learning team is fixing build validation errors on docs.microsoft.com. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. I’d very much appreciate your timely review and feedback on these changes I’ve suggested. Thanks!

**Comment by tfosmark** [comment]
@annmariehitchcock Please address the merge conflicts. Thanks!

**Comment by tfosmark** [comment]
@annmariehitchcock Please address the merge conflicts. Thanks!

**Comment by annmariehitchcock** [comment]
Conflicts were resolved. Thank you!

**Review by tfosmark — APPROVED** [review]

**Pull request closed without merging**
