### PR TITLE
chore: Convert Setext H1 to ATX

### PR DESCRIPTION
**Pull request by nschonni**
Using VS Code regex find/replace.
Find: (.*)\n====================\n
Replace: # $1\n\n

### CODE REVIEW

**Comment by nschonni** [comment]
@mairaw figured out the regex

**Comment by mairaw** [comment]
I can help with the reviews here but can you resolve conflicts on the pending PRs?

**Comment by nschonni** [comment]
these cleanups are alot simpler now that there is a `--fix` in the markdownlint-cli package. Do you folks have a baseline markdownlint.json file now? that tends to be the slowest part of starting to cleanup a repo

**Comment by mairaw** [comment]
Not sure. I was just trying to help @shirhatti. Maybe use the same as https://github.com/dotnet/docs/blob/master/.markdownlint.json?

**Pull request merged**
