### PR TITLE
Update using-php-manager-for-iis-to-setup-and-configure-php.md

### PR DESCRIPTION
**Pull request by lextm**
Fixed linked images, and changed download link to point to new location.

I start to take over the PHP Manager project on GitHub, and would like to modify this article to reflect the changes.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@lextm  please review my 2 commits. We don't allow local `/en` unless it's required. I checked a couple URLs without it and they worked.

@shirhatti please review. This is a significant improvement.

**Comment by Rick-Anderson** [comment]
@ruslany please review

**Comment by Rick-Anderson** [comment]
@lextm  is this PR still OK? Hopefully I can get someone to review it in the next week.

**Comment by lextm** [comment]
@Rick-Anderson My only remaining concern is that this article still says IIS 7.0 and above is supported.

In fact IIS 7.0 and 7.5 are now end of life. But maybe that should be fixed site wide in other pull requests.

**Comment by shirhatti** [comment]
Looks good. I'd add a note somewhere is in document that PHP Manager is not a Microsoft-owned/supported product.

@lextm, I can't thank you enough. Not just for making this change, but for maintaining PHP Studio. 🙌

**Comment by Rick-Anderson** [comment]
> Looks good. I'd add a note somewhere is in document that PHP Manager is not a Microsoft-owned/supported product.

@shirhatti  would you like me to take care of that?

**Pull request merged**
