### PR TITLE
Corrected main toc entries for express

### PR DESCRIPTION
**Pull request by ryanmajidi**

### CODE REVIEW

**Comment by shirhatti** [comment]
@ryanmajidi Is this good to merge?

**Comment by shirhatti** [comment]
This PR regresses some of the changes we already made in this branch. For example you regressed the changes made to the docfx.json file

**Comment by shirhatti** [comment]
Can you make the rename changes in a separate PR from the rest of the changes so it's possible to review the changes? There's no way I can review this

**Comment by ryanmajidi** [comment]
@shirhatti Sorry about that I didn't realize this PR was still open. All of the subsequent commits got rolled in.  I will split this up.

**Pull request closed without merging**
