### PR TITLE
Revert "IIS-docs: SFI Image Sev 1-2 Fixes"

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Reverts MicrosoftDocs/iis-docs#1068

I'm reverting this for now. If the loop-back address isn't on the approved list, we need to get that added.

The pic's deleted with the password obscured shouldn't be deleted without @John-Hart approval.  Our mandate is to warn and recommend the most secure authentication flow. IIS Mgr doesn't have a mechanism to store secrets in a key vault AFAIK.

We have too many customers using IIS and IIS Mgr to just delete all those images.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@lextm please review

**Review by tdykstra — APPROVED** [review]

**Comment by wadepickett** [comment]
@tdykstra and @Rick-Anderson 

I don't understand revert reasoning (but need to since I am doing more of these).  As stated in https://github.com/MicrosoftDocs/iis-docs/pull/1068 PR the few images deleted were ones verified to be **orphans**, not actually referenced by any document.

The rest in that PR had specific details removed per the SFI instruction.

**Comment by Rick-Anderson** [comment]
What you wrote:

Fixing all SFI severity 1-2 images.
Also, deleting a few SFI images where

I saw more than a few deleted images.

**Comment by Rick-Anderson** [comment]
Delete orphans in a separate PR
otherwise it's too hard to guess the reason something is delete3ed

**Comment by wadepickett** [comment]
I said why in the PR, you don't have to guess.  They were deleted because they were not referenced by any content.

**Comment by Rick-Anderson** [comment]
The orphans weren't identified so I had to guess and there were more than a few. Guessing is not verifying.

Do 2 PR, orphans and another problematic images. State what you will replace the deleted image with

**Comment by wadepickett** [comment]
"State what you will replace the deleted image **with**"

Rick, I did not delete any images except orphaned images that were not referenced by anything, as I indicated.   Orphaned images would not be replaced with anything, since they are orphaned image, images not referenced by any topic.  This is kinda making a mountain out of a molehill when even the molehill did not exist to begin with.

**Comment by fatmasamuk** [comment]
Anldom

28 Eki 2024 Pzt 00:25 tarihinde Wade Pickett ***@***.***>
şunu yazdı:

**Comment by fatmasamuk** [comment]
I don't understand anything

28 Eki 2024 Pzt 00:36 tarihinde fatma samuk ***@***.***> şunu
yazdı:

**Pull request merged**
