### PR TITLE
Removed obsolete contents related to WebMatrix/WebPI

### PR DESCRIPTION
**Pull request by lextm**
#1011 and #46 are about the obsolete products WebPI and WebMatrix.

While there are tons of other references remaining, this pull requests remove most of the sections and their links.

Will send more pull requests to clean up the remaining items.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@lextm if you can fix the merge conflict I'll merge this.

**Comment by lextm** [comment]
Sure. I will work on it.

**Comment by lextm** [comment]
@Rick-Anderson I have rebased the commits. You can review again now.

**Comment by Rick-Anderson** [comment]
Darn, it's got merge conflicts again. Once you clean this up, can you email me directly?
`riande@microsoft.com`

**Review by tdykstra — APPROVED** [review]

**Pull request merged**
